### ISSUE TITLE
Scala 2.12 support

### ISSUE THREAD

**Issue by alex3kov** [mattroberts297/slf4s#16]
I'm getting this on Scala 2.12.0 and sbt 0.13.13:
```
error] Exception in thread "main" java.lang.NoSuchMethodError: org.slf4s.Logging.$init$(Lorg/slf4s/Logging;)V
[error] 	at syncgtd.Main$.<init>(Main.scala:5)
[error] 	at syncgtd.Main$.<clinit>(Main.scala)
[error] 	at syncgtd.Main.main(Main.scala)
java.lang.RuntimeException: Nonzero exit code returned from runner: 1
	at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error] (compile:run) Nonzero exit code returned from runner: 1
```
Same code works perfectly on 2.11.8

**Comment by kamilkloch** [comment]
Yes, build for Scala 2.12 would be much appreciated.

**Comment by kamilkloch** [comment]
Any timeline? :)

**Comment by provegard** [comment]
I've created a 2.12 version here:

https://github.com/provegard/slf4s/tree/2.12

I'd be happy to open a PR, but I need a 2.12 branch in this repo to target. Or I can target the 2.11 branch and you can sort it out manually @mattroberts297. Whatever works for you. :)

A 2.12 build (via the [2.12-jitpack](https://github.com/provegard/slf4s/tree/2.12-jitpack) branch, since a JitPack YML file was needed) is available at JitPack. I have tested it successfully with the following dependency in my Gradle build file:

```
dependencies {
  compile 'com.github.provegard:slf4s:2cbc154cf095d9e2027bf978502bb7443afcfdf3'
}
```

**Comment by ngocdaothanh** [comment]
@provegard 

You don't need to add that YML file. It's better to add to build.sbt:

```
javacOptions ++= Seq("-source", "1.8", "-target", "1.8")
```

Can you release a version to Sonatype (Maven Central)?

I think this repo is not maintained any more, because there are several other simple issues in this repo, but they haven't been not commented on or resolved yet.

Please also update SLF4J version to the latest.

**Comment by provegard** [comment]
I'll look into it. Busy this week though.

**Comment by ngocdaothanh** [comment]
I can't wait so I've forked and released a version for Scala 2.12:
https://github.com/xitrum-framework/slf4s

**Comment by provegard** [comment]
@ngocdaothanh do you plan on actively maintain that repo?

**Comment by mattroberts297** [comment]
@alex3kov, @kamilkloch, @ngocdaothanh, @provegard, sorry for the delay. I promoted this evening, should be available to search soon:

```
Group: org.slf4s
Artifact: slf4s-api_2.12
Version: 1.7.25
```

I also setup CD and will create a separate issue asking for maintainers because sometimes work / life means I can't pay as much attention to this as I would like. One thing I need to do is sense-check Travis CIs behaviour re: my secrets. Closing for now, but any issues i.e. it doesn't appear in search then please reopen.
